Sklep/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from shop import views
from shop.models import Product, Client, Delivery, Basket, Order, ProductInOrder

from django.contrib.admin.sites import AlreadyRegistered

from shop.views import ProductDetailView, ProductUpdateView, ProductCreateView, ProductDeleteView, SignUpView, \
    SubmittableLoginView, SubmittablePasswordChangeForm, ProductView, OrderCreateView, AddOrderView, OrderView

try:
    admin.site.register(Product)
    admin.site.register(Client)
    admin.site.register(Delivery)
    admin.site.register(Basket)
    admin.site.register(Order)
    admin.site.register(ProductInOrder)
except AlreadyRegistered:
    pass



urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('password_change/', SubmittablePasswordChangeForm.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('passwrod_reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('admin/', admin.site.urls),
    path('', ProductView.as_view(), name='products'),
    path('products/details/<id>', ProductDetailView.as_view(), name='product_details'),
    path('products/create/', ProductCreateView.as_view(), name='product_add'),
    path('products/delete/<pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('products/update/<pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('order/create/', OrderCreateView.as_view(), name='order_create'),
    path('order/add/<product_id>', AddOrderView.as_view(), name='order_add'),
    path('order/details/', OrderView.as_view(), name='order_details'),
    # path('basket/delete/<int:product_id>', views.basket_remove, name='basket_delete'),
    # path('basket/update/', BasketUpdateView.as_view(), name='basket_edit'),
    # path('purchse/', BasketUpdateView.as_view(), name='purchase'),
]

shop/models.py
from django.contrib.auth.models import User
from django.db.models import (Model,
                              CharField, DateField, DateTimeField, IntegerField, DecimalField, TextField,
                              ForeignKey, DO_NOTHING, OneToOneField, CASCADE, ManyToManyField)
# Create your models here.


class Product(Model):
    category = CharField(max_length=128)
    name = CharField(max_length=300, null=True)
    photo = CharField(max_length=128, null=True)
    description = TextField(null=True)
    amount = IntegerField(default=0)
    price = DecimalField(max_digits=10, decimal_places=2)


class Client(Model):
    name = CharField(max_length=128)
    surname = CharField(max_length=128)
    street = CharField(max_length=128)
    home_number = CharField(max_length=128)
    flat_number = CharField(max_length=128)
    postcode = CharField(max_length=128)
    locality = CharField(max_length=128)
    country = CharField(max_length=128)
    mail = CharField(max_length=128)
    phone_number = CharField(max_length=128)


class Delivery(Model):
    delivery_company = CharField(max_length=128)
    delivery_price = DecimalField(max_digits=5, decimal_places=2)


class Basket(Model):
    product = ForeignKey(Product, on_delete=DO_NOTHING)
    amount = IntegerField(default=0)
    client = ForeignKey(Client, on_delete=DO_NOTHING)


class Order(Model):
    delivery = ForeignKey(Delivery, on_delete=DO_NOTHING, null=True)
    name = CharField(max_length=300, null=True)
    amount = IntegerField(default=0, null=True)
    price = DecimalField(max_digits=10, decimal_places=2, null=True)
    client = ForeignKey(Client, on_delete=DO_NOTHING, null=True)
    date_order = DateTimeField(auto_now_add=True)
    products = ManyToManyField(Product)


class ProductInOrder(Model):
    order = ForeignKey(Order, on_delete=DO_NOTHING)
    product = ForeignKey(Product, on_delete=DO_NOTHING)
    amount = IntegerField(default=0)


class Profile(Model):
    user = OneToOneField(User, on_delete=CASCADE)
    street = CharField(max_length=128)
    home_number = CharField(max_length=128)
    flat_number = CharField(max_length=128)
    postcode = CharField(max_length=128)
    locality = CharField(max_length=128)
    country = CharField(max_length=128)
    phone_number = CharField(max_length=128)

shop/forms.py
from logging import getLogger

from django.contrib.auth.forms import UserCreationForm
from django.db.models import TextField
from django.db.transaction import atomic

LOGGER = getLogger()
from django.forms import (
    ModelForm, CharField, ModelChoiceField, IntegerField, DateField, Textarea, DecimalField, Form, TypedChoiceField,
    BooleanField, HiddenInput
)

from shop.models import Product, Client, Delivery, Basket, Order, ProductInOrder, Profile

# from viewer.validators import PastMonthField, capitalized_validator
from django.core.exceptions import ValidationError

import re

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class BasketAddProductForm(Form):
    quantity = TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = BooleanField(required=False, initial=False, widget=HiddenInput)


class ProductForm(ModelForm):
    class Meta:  # subklasa opisująca dane z których będzie tworzy form
        model = Product  # model na podstawie tworzymy formularz
        fields = '__all__'  # wykorzystujemy wszystkie pola z modelu

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean_description(self):
        # pobranie wartości pola description
        initial = self.cleaned_data['description']
        # podział tekstu na części "od kropki do kropki" na zdania
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        # zamina na wielką literę pierwszj litery każdego ze zdań,
        # dodanie kropki, powtórzenie operacji dla kolejnego zdania
        return '.'.join(sentence.capitalize() for sentence in sentences)


class OrderForm(ModelForm):
    class Meta:  # subklasa opisująca dane z których będzie tworzy form
        model = Order  # model na podstawie tworzymy formularz
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'



class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']

    street = CharField(
        label='Podaj ulicę', min_length=3, max_length=128
    )
    home_number = CharField(
        label='Podaj numer domu', min_length=1
    )
    flat_number = CharField(
        label='Podaj numer mieszkania', min_length=1
    )
    postcode = CharField(
        label='Podaj kod pocztowy', min_length=5
    )
    locality = CharField(
        label='Podaj miejscowość zamieszkania', min_length=3
    )
    country = CharField(
        label='Podaj kraj zamieszkania', min_length=3
    )
    phone_number = CharField(
        label='Podaj numer telefonu', min_length=3
    )

    @atomic
    def save(self, commit=True):
        self.instance.is_activate = False
        result = super().save(commit)
        street = self.cleaned_data['street']
        home_number = self.cleaned_data['home_number']
        flat_number = self.cleaned_data['flat_number']
        postcode = self.cleaned_data['postcode']
        locality = self.cleaned_data['locality']
        country = self.cleaned_data['country']
        phone_number = self.cleaned_data['phone_number']
        profile = Profile(street=street, home_number=home_number, flat_number=flat_number, postcode=postcode,
                          locality=locality, country=country, phone_number=phone_number, user=result)
        if commit:
            profile.save()
        return result


# class BasketForm(ModelForm):
#     class Meta:  # subklasa opisująca dane z których będzie tworzy form
#         model = Basket  # model na podstawie tworzymy formularz
#         fields = '__all__'  # wykorzystujemy wszystkie pola z modelu
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for visible in self.visible_fields():
#             visible.field.widget.attrs['class'] = 'form-control'

shop/views.py
from logging import getLogger

from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views import View
from django.views.decorators.http import require_POST

from shop import basket

LOGGER = getLogger()

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from shop.forms import ProductForm, SignUpForm, BasketAddProductForm, OrderForm
from shop.models import Product, Order
# from shop.basket import Basket


class ProductView(ListView):
    template_name = 'products.html'
    model = Product


class ProductCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'formAddEditProduct.html'
    form_class = ProductForm
    success_url = reverse_lazy('products')
    permission_required = 'shop.product_add'

    # co dzieje się, gdy formularz nie przejdzie walidacji:
    def form_invalid(self, form):
        # odkładamy w logach informacje o operacji
        LOGGER.warning('User provided invalid data')
        # zwraca wynik działania pierwotnej funkcji form_invalid
        return super().form_invalid(form)


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'formAddEditProduct.html'
    form_class = ProductForm
    # adres pobrany z UrLs który zostaniemy przekierowanina
    # gdy aktualizacja się powiedzie (index pochodzi z name!)
    success_url = reverse_lazy('products')
    # Nazwa encji z której będziemy
    model = Product
    permission_required = 'shop.product_edit'
    LOGGER.warning('User provided invalid data')

    # co dzieje się, gdy formularz nie przejdzie walidacji:
    def form_invalid(self, form):
        # odkładamy w logach informacje o operacji
        LOGGER.warning('User provided invalid data')
        # zwraca wynik działania pierwotnej funkcji form_invalid
        return super().form_invalid(form)


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'product_delete.html'
    success_url = reverse_lazy('products')
    # Nazwa necji z której będziemy kasować rekord
    model = Product
    permission_required = 'shop.product_delete'


class ProductDetailView(View):
    def get(self, request, id):
        return render(
            request, 'product_details.html',
            context={'products': Product.objects.get(id=id)}
        )


class SubmittableLoginView(LoginView):
    template_name = 'form.html'


class SubmittablePasswordChangeForm(PasswordChangeView):
    template_name = 'form.html'
    success_url = reverse_lazy('products')


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'form.html'
    success_url = reverse_lazy('products')


class OrderCreateView(CreateView):
    template_name = 'order_create.html'
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('products')


class OrderView(View):
    def get(self, request):
       return render(
            request, 'order_details.html',
            context={'orders': Order.objects.all()}
        )


class AddOrderView(View):
    template_name = 'order_add.html'
    # model = Order
    # form_class = OrderForm
    success_url = reverse_lazy('products')

    def get(self, request, product_id):
        product = Product.objects.filter(id=product_id).first()
        order = Order.objects.get(id=request.GET.get("zamowienie_id"))
        order.products.add(product)
        order.save()






# @require_POST
# def basket_add(request, product_id):
#     basket = Basket(request)
#     product = get_object_or_404(Product, id=product_id)
#     form = BasketAddProductForm(request.POST)
#     if form.is_valid():
#         cd = form.cleaned_data
#         basket.add(product=product, amount=cd['amount'], update_amount=cd['update'])
#     return redirect('basket:basket_detail')
#
#
# @require_POST
# def basket_remove(request, product_id):
#     basket = Basket(request)
#     product = get_object_or_404(Product, id=product_id)
#     basket.remove(product)
#     return redirect('basket:basket_detail')
#
#
# def basket_detail(request):
#     basket = Basket(request)
#     return render(request, 'basket_details.html', {'basket': basket})


# class BasketCreateView(PermissionRequiredMixin, CreateView):
#     template_name = 'formAddEditBasket.html'
#     form_class = Basket
#     success_url = reverse_lazy('basket_add')
#     permission_required = 'shop.basket_add'
#
#
# class BasketUpdateView(PermissionRequiredMixin, UpdateView):
#     template_name = 'formAddEditBasket.html'
#     form_class = Basket
#     success_url = reverse_lazy('basket_edit')
#     model = Basket
#     permission_required = 'shop.basket_edit'
#     LOGGER.warning('User provided invalid data')
#
#     def form_invalid(self, form):
#         LOGGER.warning('User provided invalid data')
#         return super().form_invalid(form)
#
#
# class BasketDeleteView(PermissionRequiredMixin, DeleteView):
#     template_name = 'basket_delete.html'
#     success_url = reverse_lazy('basket_delete')
#     model = Basket
#     permission_required = 'shop.basket_delete'
#
#
# class BasketDetailView(View):
#     def get(self, request, id):
#         return render(
#             request, 'basket_details.html',
#             context={'basket': Product.objects.get(id=id)}
#         )
#
#
# class PurchaseView(PermissionRequiredMixin, UpdateView):
#     template_name = 'fromAddEditBasket.html'
#     success_url = reverse_lazy('purchase')
#     model = Basket
#     permission_required = 'shop.purchase'
#
#
# class ProductClassificationView(PermissionRequiredMixin, UpdateView):
#     template_name = 'formAddEditProduct.html'
#     success_url = reverse_lazy('product_classification')
#     model = Basket
#     permission_required = 'shop.product_classification'
#
#
# class BasketDetailView(View):
#     def get(self, request, id):
#         return render(
#             request, 'baket_details.html',
#             context={'basket': Product.objects.get(id=id)}
#         )

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html {% if LANGUAGE_CODE %} lang="{{ LANGUAGE_COD }}" {% endif %} >
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {%  if user.is_authenticated %}
                <div>
                    {% if user.first_name %}Cześć, {{ user.first_name }}
                    {% else %}Cześć, {{ user.username }} {% endif %}
                </div>
            {% endif %}

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}">Wyloguj</a>
                        <a class="nav-link" href="{% url 'password_change' %}">Zmień hasło</a>
{#                        <a class="nav-link" href="{% url 'basket_add' %}">Dodaj do koszyka</a>#}
{#                        <a class="nav-link" href="{% url 'basket_delete' %}">Usuń koszyk</a>#}
{#                        <a class="nav-link" href="{% url 'basket_edit' %}">Edytuj koszyk</a>#}
{#                        <a class="nav-link" href="{%  url 'purchase' %}">Złóż zamówienie</a>#}
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}">Zaloguj</a>
                        <a class="nav-link" href="{% url 'sign_up' %}">Zarejestruj się</a>
                    {% endif %}

                    {% if user.is_staff %}
                        <a class="nav-link" href="{%  url 'product_add' %}">Dodaj produkt</a>
                        <a class="nav-link" href="{%  url 'order_create' %}">Stwórz zamówienie</a>
                        <a class="nav-link" href="{%  url 'order_details' %}">Zobacz zamówienie</a>


                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="jumbotron">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

shop/templates/basket.html
{% extends "base.html" %}

{% block title %}
    Twój koszyk
{% endblock %}

{% block content %}
    <h1>To są produkty w twoim koszyku</h1>
    {% for basket in object_list %}
        <li>
            <a href="{% url 'basket_details' basket.id %}">{{ basket.product.category }}</a>
                 - {{basket.product.price}} zł - {{basket.amount}} szt. - {{ basket.product.description }}
            <a href="{% url 'basket_edit' basket.id %}">(Edytuj koszyk)</a>
            <a href="{% url 'basket_delete' basket.id %}">(Usuń z koszyka)</a>
        </li>

    {% endfor %}
{% endblock %}

shop/templates/basket_delete.html
{% extends "base.html" %}

{% block title %} Usuwanie produktu z koszyka {% endblock %}

{% block content %}
    {% if user.is_staff %}
    <form method="post">
        {% csrf_token %}
        <p>
            Are you sure want to delete this product "{{ object.product.category }}"?
        </p>
        <input type="submit" value="Yes" class="btn btn-danger">
    </form>
    {% endif %}

{% endblock %}

shop/templates/basket_details.html
{#{% extends "base.html" %}#}
{##}
{#{% block title %}#}
{#    Kategoria: {{ basket.products.category }}#}
{#{% endblock %}#}
{##}
{#{%  block content %}#}
{#    <h1>{{ basket.products.category }}</h1>#}
{#    <div> <strong>Cena: </strong>{{ basket.products.price }} zł</div>#}
{#    <div> <strong>Ilość: </strong>{{ basket.amount }} szt.</div>#}
{#{% endblock %}#}
{% extends "base.html" %}
{% load static %}
{% block title %}
    Koszyk na zakupy
{% endblock %}
{% block content %}
    <h1>Koszyk na zakupy</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Obraz</th>
                <th>Produkt</th>
                <th>Ilość</th>
                <th>Usuń</th>
                <th>Cena jednostkowa</th>
                <th>Kwota</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
{#                        <td>#}
{#                            <a href="{{ product.get_absolute_url }}">#}
{#                                <img src="{% if product.image %}{{ product.image.url }}{% else %} {% static "img/no_image.png" %}{% endif %}">#}
{#                            </a>#}
{#                        </td>#}
                        <td>{{ product.category }}</td>
                        <td>{{ item.amount }}</td>
                        <td><a href="{% url "basket:basket_remove" product.id %}">Usuń</a></td>
                        <td class="num">{{ item.price }} zł</td>
                        <td class="num">{{ item.total_price }} zł</td>
                    </tr>
                {% endwith %}
            {% endfor %}
                <tr class="total">
                    <td>Wartość całkowita</td>
                    <td colspan="4"></td>
                    <td class="num">{{ cart.get_total_price }} zł</td>
                </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Kontynuuj zakupy</a>
        <a href="#" class="button">Do kasy</a>
    </p>
{% endblock %}

shop/templates/form.html
{% extends "base.html" %}

{% block title %}

{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Zapisz"
           class="btn btn-primary">
    </form>
{% endblock %}

shop/templates/formAddEditBasket.html
{% extends "base.html" %}

{% block title %}
    Dodaj do koszyka
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

         <div class="form-group">
            <!-- Produkt -->
            {{ form.basket.product_category.errors }}
            <label for="{{ form.basket.product_category.id_for_label }}">Produktu</label>
            {{ form.product_category }}
        </div>

        <div class="form-row">
            <!-- Ilość -->
            <div class="form-group col-md-4">
                {{ form.basket_amount.errors }}
                <label for="{{ form.basket_amount.id_for_label }}">Ilość</label>
                {{ form.basket_amount }}

            </div>
            <input type="range" value="Wybierz ilość" class="btn btn-primary">
            <!-- Klient -->
            <div class="form-group col-md-4">
                {{ form.client.errors }}
                <label for="{{ form.client.id_for_label }}">Klient</label>
                {{ form.client.id }}
            </div>
        </div>
    </form>
{% endblock %}

shop/templates/formAddEditProduct.html
{% extends "base.html" %}

{% block title %}
    Dodaj produkt
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <!-- Nazwa produktu -->
            {{ form.product_name.errors }}
            <label for="{{ form.product_name.id_for_label }}">Nazwa produktu</label>
            {{ form.product_name }}
        </div>

        <div class="form-row">
            <!-- Kategoria -->
            <div class="form-group col-md-4">
                {{ form.name.errors }}
                <label for="{{ form.category.id_for_label }}">Kategoria</label>
                {{ form.category }}
            </div>
                       <!-- Nazwa -->
            <div class="form-group col-md-4">
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Nazwa</label>
                {{ form.name }}
            </div>
                        <!-- Zdjęcia -->
            <div class="form-group col-md-4">
                {{ form.photo.errors }}
                <label for="{{ form.photo.id_for_label }}">Zdjęcia</label>
                {{ form.photo }}

            </div>
            <input type="image" value="Wybierz zdjęcie" class="btn btn-primary">
        </div>
            <!-- Opis produktu -->
        <div class="form-group">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}">Opis</label>
            {{ form.description }}
        </div>


            <!-- Ilość -->
        <div class="form-group col-md-4">
            {{ form.amount.errors }}
            <label for="{{ form.amount.id_for_label }}">Ilość</label>
            {{ form.amount }}
        </div>
{#        <input type="range" value="Wybierz ilość" class="btn btn-primary">#}

         <!-- Cena -->
        <div class="form-group col-md-4">
            {{ form.price.errors }}
            <label for="{{ form.price.id_for_label }}">Cena</label>
            {{ form.price }}
        </div>
{#        <input type="number" value="Cena" class="input-group-text">#}
        <input type="submit" value="Zaakceptuj" class="btn btn-primary">
    </form>



{% endblock %}

shop/templates/order_add.html
{% extends "base.html" %}

{% block title %} Dodawanie produktu do zamówienia {% endblock %}

{% block content %}
    <form method="get">
        {% csrf_token %}
        <p>
             Produkt dodany poprawnie.
        </p>
        <input type="submit" value="Yes" class="btn btn-danger">
    </form>

{% endblock %}

shop/templates/order_create.html
{% extends "base.html" %}

{% block title %}
    Dodaj produkt
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
           {{ form.as_p }}
        {{ form.non_field_errors }}

        <div class="form-group">
            <!-- Data zamówienia -->
            {{ form.order_date_order.errors }}
            <label for="{{ form.order_date_order.id_for_label }}">Data zamówienia</label>
            {{ form.order_date_order }}
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <!-- Nazwa produktu -->
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Nazwa produktu</label>
                {{ form.product_name }}
            </div>
            <!-- Ilość -->
            <div class="form-group col-md-4">
                {{ form.amount.errors }}
                <label for="{{ form.amount.id_for_label }}">Kategoria</label>
                {{ form.amount }}
            </div>
                       <!-- Cena -->
            <div class="form-group col-md-4">
                {{ form.price.errors }}
                <label for="{{ form.price.id_for_label }}">Cena</label>
                {{ form.price }}
            </div>
        </div>

        <input type="submit" value="Zaakceptuj" class="btn btn-primary">
    </form>



{% endblock %}

shop/templates/order_details.html
{% extends "base.html" %}

{% block title %}
    Lista zamówionych produktów
{% endblock %}

{% block content %}
    <h1>Twoje zamówienie:</h1>

        {% for order in orders %}
            <li>
                {{ order.name }}
{#                {% for product in order.products %}#}
{#                    {{ product.name }}#}
{#                {% endfor %}    #}
            </li>

        {% endfor %}

{% endblock %}

shop/templates/product_delete.html
{% extends "base.html" %}

{% block title %} Usuwanie produktu {% endblock %}

{% block content %}
    {% if user.is_staff %}
    <form method="post">
        {% csrf_token %}
        <p>
            Are you sure want to delete this product "{{ object.name }}"?
        </p>
        <input type="submit" value="Yes" class="btn btn-danger">
    </form>
    {% endif %}

{% endblock %}

shop/templates/product_details.html
{% extends "base.html" %}

{% block title %}
    Lista zamówionych produktów
{% endblock %}

{% block content %}
    <h1>Twoje zamówienie:</h1>
    {% for order in object_list %}
        <li>
            <a href="{% url 'order_details' products.id %}">{{ product.category }}</a>
                 {{ products.name }} - {{products.price}} zł - {{products.amount}} szt.

        </li>

    {% endfor %}
{% endblock %}

shop/templates/products.html
{% extends "base.html" %}

{% block title %}
    Lista produktów
{% endblock %}

{% block content %}
    <h1>Witaj w naszym sklepie ! Zarządzaj produktami w swoim sklepie</h1>
    <form>
    <input name="zamowienie_id">
        {% for product in object_list %}
            <li>
                <a href="{% url 'product_details' product.id %}">{{ product.category }}</a>
                     {{ product.name }} - {{product.price}} zł - {{product.amount}} szt. - {{ product.description }}
                {% if user.is_staff %}
                    <a href="{% url 'product_edit' product.id %}">(Edytuj)</a>
                    <a href="{% url 'product_delete' product.id %}">(Usuń)</a>
                {% endif %}
                    <button formaction="{% url 'order_add' product.id %}" type="submit">(Dodaj do zamówienia)</button>
            </li>

        {% endfor %}
    </form>
{% endblock %}